### ISSUE TITLE
Language service dont work for the tool

### ISSUE THREAD

**Issue by Icarussakka** [gmodWare/gware-lang#2]
When you connect to the server, you get instantly an error because "L is a nil value". I dont know how to fix that.
Please have a look @MenschlichTv

**Comment by MenschlichTv** [comment]
I assume this code is executed before the languages are loaded, use the hook to save the strings somewhere

**Comment by MenschlichTv** [comment]
[gware-utils] addons/gware-utils/lua/weapons/gmod_tool/stools/sh_job_spawner.lua:16: attempt to call local 'L' (a nil value)
  1. unknown - addons/gware-utils/lua/weapons/gmod_tool/stools/sh_job_spawner.lua:16
   2. include - [C]:-1
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua:142
     4. include - [C]:-1
      5. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:353
       6. include - [C]:-1
        7. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:11
